wandb_version: 1

epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 100
lr:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1685832256.045842
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.9
      5: 0.15.3
      8:
      - 1
      - 3
      - 5
